version: '3'

services:
  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - /app/node_modules
      - ./transaction-service:/app
